[package]
name = "url-shortener"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.9.0"
rusqlite = "0.33.0"
r2d2 = "0.8"
r2d2_sqlite = "0.26"
